### ISSUE TITLE
Clarify licensing: GPLv2 or GPLv2+

### ISSUE THREAD

**Issue by akien-mga** [eugeneloza/Mazer#1]
The simple presence of the GPLv2 text in the LICENSE file is not enough to tell whether you code is strictly licensed under the GPL version 2, or the GPL version 2 (or any later version), i.e. GPLv2+.

The simple solution is to clarify this in the README.md. A better solution would be to also put a header in each code file that clarifies copyright and versions, like e.g.: https://github.com/OpenDungeons/OpenDungeons/blob/development/source/main.cpp#L6-L19
For my own little game I've made the header a bit shorter: https://github.com/akien-mga/dynadungeons/blob/master/scripts/player.gd#L1-L10

**Comment by eugeneloza** [comment]
Oh... thanks a lot!
I'm a newbie in all that licensing stuff. I've just selected an 'appropriate free license'.
I'll try to include all this asap.

**Comment by akien-mga** [comment]
I'd advise you GPLv2+ over a strict GPLv2 then, because the latter would not be compatible with GPLv3 stuff.

**Comment by eugeneloza** [comment]
Maybe it should be GPLv3 better? I don't really know the difference :)
As far as I remember, sourceforge proposed GPL3 by default, and github gives GPL2 as default free license.

**Comment by akien-mga** [comment]
Yes if you don't have a strong opinion I would advise you to use GPLv3+, i.e. "GPL version 3 or (at your option) any later version". For some projects it can be problematic to give full confidence in what the FSF might produce for a future GPLv4, but IMO there is not much risk that the FSF turns evil, or at least the impact on a game like Mazer should not be too high :)

**Comment by eugeneloza** [comment]
Thanks a lot. I'll use GPL v.3 then.
I just want to keep things free and simple. Like CC-BY(OGA-BY) for media files.

**Comment by eugeneloza** [comment]
closed via 87789348271cf708f922536ab79a87385504a4bd
